services:
  minecraft:
    container_name: minecraft
    ports:
      - 25565:25565/tcp
      - 25565:25565/udp
    volumes:
      - minecraft:/data
    stdin_open: true
    tty: true

    build: ./minecraft

  project-zomboid:
      container_name: project-zomboid
      ports:
        - 16261:16261/udp
        - 16261:16261/tcp
        - 16262:16262/udp
      volumes:
        - project-zomboid-game:/data
        - project-zomboid-saves:/root/Zomboid
      stdin_open: true
      tty: true
      build: ./project-zomboid


volumes:
  minecraft:
  project-zomboid-game:
  project-zomboid-saves: