services:
  minecraft:
    container_name: minecraft
    ports:
      - 25565:25565
    volumes:
      - minecraft:/data
    stdin_open: true
    tty: true

    build: ./minecraft

  project-zomboid:
    container_name: project-zomboid
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
    volumes:
      - project-zomboid:/data
    stdin_open: true
    tty: true

    build: ./project-zomboid


volumes:
  minecraft:
  project-zomboid: